science/colt: pin to openjdk8
It fails on jdk21:
error: as of release 9, '_' is a keyword, and may not be used as an identifier

Build.xml also needed an encoding="ISO-8859-1" in the javac target.

NB: Upstream didn't make a release since 2004.

PR:	272855
Approved-by:	no maintainer