Switch to gcc temporarily as building with clang leads to linker errors:
[ 51%] Linking CXX shared library libkwavegui.so
cd /wrkdirs/usr/ports/audio/kwave/work/.build/libgui && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/libkwavegui.dir/link.txt --verbose=1
/usr/local/libexec/ccache/c++ -fPIC -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC --std=c++11 -std=c++0x -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -O2 -pipe -fstack-protector -fno-strict-aliasing -Wl,--export-dynamic -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags -L/usr/local/lib -fstack-protector -shared -Wl,-soname,libkwavegui.so.17 -o libkwavegui.so.17.04.2 CMakeFiles/libkwavegui.dir/Colors.cpp.o CMakeFiles/libkwavegui.dir/CurveWidget.cpp.o CMakeFiles/libkwavegui.dir/FileDialog.cpp.o CMakeFiles/libkwavegui.dir/FilterPlugin.cpp.o CMakeFiles/libkwavegui.dir/FrequencyResponseWidget.cpp.o CMakeFiles/libkwavegui.dir/HMSTimeWidget.cpp.o CMakeFiles/libkwavegui.dir/ImageView.cpp.o CMakeFiles/libkwavegui.dir/InvertableSpinBox.cpp.o CMakeFiles/libkwavegui.dir/LabelItem.cpp.o CMakeFiles/libkwavegui.dir/LabelPropertiesWidget.cpp.o CMakeFiles/libkwavegui.dir/MenuNode.cpp.o CMakeFiles/libkwavegui.dir/MenuGroup.cpp.o CMakeFiles/libkwavegui.dir/MenuItem.cpp.o CMakeFiles/libkwavegui.dir/MenuList.cpp.o CMakeFiles/libkwavegui.dir/MenuSub.cpp.o CMakeFiles/libkwavegui.dir/MenuRoot.cpp.o CMakeFiles/libkwavegui.dir/MenuManager.cpp.o CMakeFiles/libkwavegui.dir/MouseMark.cpp.o CMakeFiles/libkwavegui.dir/MultiStateWidget.cpp.o CMakeFiles/libkwavegui.dir/OverViewCache.cpp.o CMakeFiles/libkwavegui.dir/OverViewWidget.cpp.o CMakeFiles/libkwavegui.dir/ScaleWidget.cpp.o CMakeFiles/libkwavegui.dir/SelectionBorderItem.cpp.o CMakeFiles/libkwavegui.dir/SelectionItem.cpp.o CMakeFiles/libkwavegui.dir/SelectionTracker.cpp.o CMakeFiles/libkwavegui.dir/SelectTimeWidget.cpp.o CMakeFiles/libkwavegui.dir/SignalView.cpp.o CMakeFiles/libkwavegui.dir/SignalWidget.cpp.o CMakeFiles/libkwavegui.dir/TrackPixmap.cpp.o CMakeFiles/libkwavegui.dir/TrackView.cpp.o CMakeFiles/libkwavegui.dir/TreeWidgetWrapper.cpp.o CMakeFiles/libkwavegui.dir/ViewItem.cpp.o CMakeFiles/libkwavegui.dir/libkwavegui_autogen/moc_compilation.cpp.o  -L/wrkdirs/usr/ports/audio/kwave/work/.build/libgui  -L/wrkdirs/usr/ports/audio/kwave/work/.build/libkwave -Wl,-rpath,/wrkdirs/usr/ports/audio/kwave/work/.build/libgui:/wrkdirs/usr/ports/audio/kwave/work/.build/libkwave:/usr/local/lib:/usr/local/lib/qt5: -lkwave /usr/local/lib/libKF5KIOFileWidgets.so.5.35.0 /usr/local/lib/libKF5KIOWidgets.so.5.35.0 /usr/local/lib/libKF5KIOCore.so.5.35.0 /usr/local/lib/qt5/libQt5Concurrent.so.5.7.1 /usr/local/lib/libKF5JobWidgets.so.5.35.0 /usr/local/lib/libKF5Bookmarks.so.5.35.0 /usr/local/lib/libKF5XmlGui.so.5.35.0 /usr/local/lib/qt5/libQt5Network.so.5.7.1 /usr/local/lib/libKF5IconThemes.so.5.35.0 /usr/local/lib/libKF5Service.so.5.35.0 /usr/local/lib/libKF5Completion.so.5.35.0 /usr/local/lib/libKF5ConfigWidgets.so.5.35.0 /usr/local/lib/libKF5I18n.so.5.35.0 /usr/local/lib/libKF5WidgetsAddons.so.5.35.0 /usr/local/lib/libKF5ConfigGui.so.5.35.0 /usr/local/lib/libKF5ConfigCore.so.5.35.0 /usr/local/lib/libKF5Auth.so.5.35.0 /usr/local/lib/libKF5CoreAddons.so.5.35.0 /usr/local/lib/libKF5Codecs.so.5.35.0 /usr/local/lib/libKF5ItemViews.so.5.35.0 /usr/local/lib/libKF5Solid.so.5.35.0 /usr/local/lib/qt5/libQt5Widgets.so.5.7.1 /usr/local/lib/qt5/libQt5Gui.so.5.7.1 /usr/local/lib/qt5/libQt5DBus.so.5.7.1 /usr/local/lib/qt5/libQt5Xml.so.5.7.1 /usr/local/lib/qt5/libQt5Core.so.5.7.1 -Wl,-rpath-link,/usr/local/lib
CMakeFiles/libkwavegui.dir/OverViewCache.cpp.o: In function `Kwave::OverViewCache::getMinMax(int, QVector<Kwave::OverViewCache::MinMax>&)':
/wrkdirs/usr/ports/audio/kwave/work/kwave-17.04.2/libgui/OverViewCache.cpp:(.text+0x2127): undefined reference to `Kwave::MultiTrackSource<Kwave::SampleReader, false>::operator[](unsigned int)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)