audio/noctavox: Add runtime dependency
- Add audio/alsa-plugins to RUN_DEPENDS, because without it noctavox
  fails to start with the following error:

ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) [error.pcm] Unknown PCM oss

thread 'main' (101801) panicked at noctavox/src/player/handle.rs:18:40:
Failed to initialize backend: output error: The requested device is no longer available. For example, it has been unplugged.

- Bump PORTREVISION