net/samba423: Fix pkg-plist for option CLUSTER
    ===> Checking for items in STAGEDIR missing from pkg-plist
    Error: Orphaned: @dir var/lib/ctdb/persistent
    Error: Orphaned: @dir var/lib/ctdb/state
    Error: Orphaned: @dir var/lib/ctdb/volatile
    Error: Orphaned: @dir var/log
    Error: Orphaned: @dir var/run/ctdb
    ===> Checking for items in pkg-plist which are not in STAGEDIR
    Error: Missing: @dir /var/lib/ctdb/persistent
    Error: Missing: @dir /var/lib/ctdb/state
    Error: Missing: @dir /var/lib/ctdb/volatile
    Error: Missing: @dir /var/lib/ctdb
    Error: Missing: @dir /var/lib
    Error: Missing: @dir /var/run/ctdb

Also, address the problem with an symlink pointing to an absolute path:

    Warning: Bad symlink '/usr/local/etc/ctdb/statd-callout' pointing to an absolute pathname '/usr/local/libexec/ctdb/statd_callout'

PR:		291104
Reported by:	vvd