Disable test subdirectory in devel/plasma5-khotkeys
There is something wonky in the dependency genreation:
  khotkeys-5.10.95/app/kded.cpp:31: Error: Plugin Metadata file "khotkeys.json" does not exist. Declaration will be ignored

That file should be generated by a custom command, which the target in question already depends on. As this is only a test
application that is not even installed, simply ignore it.