chinese/gcin-qt5: Fix build with Qt 5.9.
We need to include ${includedir}/qt5/QtGui/5.9.3, not 5.9.3/QtGui:

c++ -O2 -pipe  -fstack-protector -fno-strict-aliasing  -std=c++11 -I../im-client -I/usr/local/include -I/usr/local/include/qt5 `pkg-config Qt5Core Qt5Gui Qt5DBus --cflags` -I`pkg-config --variable=includedir Qt5Gui`/QtGui/`pkg-config --modversion Qt5Gui`/QtGui -Wall -D_REENTRANT -DUNIX=1 -fPIC  -DQT5 -DQT_SHARED -DQT_IMMODULE -DPIC -DDEBUG="0"   -c -o moc_qgcinplatforminputcontext.o moc_qgcinplatforminputcontext.cpp
In file included from moc_gcin-qt5.cpp:9:
In file included from ./gcin-qt5.h:3:
/usr/local/include/qt5/QtGui/5.9.3/QtGui/qpa/qplatforminputcontextplugin_p.h:54:10: fatal error: 'QtGui/private/qtguiglobal_p.h' file not found
 #include <QtGui/private/qtguiglobal_p.h>
          ^