biology/ugene: Fix build with Qt 5.9.
Drop a '#define point "."' that is not present in more recent versions of
the port. Defining a macro with such a common name causes build issues like
this:

In file included from src/NeighborJoinAdapter.cpp:35:
In file included from src/dnadist.h:6:
In file included from /usr/local/include/qt5/QtGui/QList:1:
In file included from /usr/local/include/qt5/QtGui/qevent.h:56:
/usr/local/include/qt5/QtGui/qvector2d.h:62:55: error: expected ')'
    Q_DECL_CONSTEXPR explicit QVector2D(const QPoint& point);
                                                      ^
src/phylip.h:274:25: note: expanded from macro 'point'
 #define point           "."
                         ^